<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- Day first covered with basic stuffs!! : this is how cmt is done in html  --> 
     
</body>
</html>

<?php // this is how we start php
// this is how comment is done in php

echo "ram le khana khayo <br>"; //print stat with new line;<br>
$name="ram"; //variable declaration
echo $name; //variable print


?><!-- this is how we end php --> 