<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- Day first covered with basic stuffs!! : this is how cmt is done in html  --> 
     
</body>
</html>

<?php // this is how we start php
// this is how comment is done in php

echo "ram le khana khayo <br>"; //print stat with new line;<br>
$name="ram"; //variable declaration
echo"{$name}<br>"; //variable print

//data types
 
$name="ram"; //string
$age=10; //integer
$height_in_inch=5.7;    //float
$Active=true; //boolean

//array
$fruits=array("apple","banana","mango");
echo $fruits[0]; //apple

//operator
$a=10;
$b=20;
echo $a+$b; //30
echo $a-$b; //-10
echo $a*$b; //200
echo $a/$b; //0.5
echo $a%$b; //10

//increment and decrement
$a++; //11
$a--; //10

//comparison operator
$a=10;
$b=20;
echo $a==$b; //false
echo $a!=$b; //true
echo $a>$b; //false
echo $a<$b; //true
echo $a>=$b; //false
echo $a<=$b; //true


// string operator
$a="ram";
$b="world";
echo "{$a} to {$b} <br>"; //hello to world
echo "dear {$a}, eat your food."; // dear ram, eat your food. 

//learn about get and post method
//get method



?><!-- this is how we end php --> 